### ISSUE TITLE
[Feature request] Possibility to comment both sides in diff mode

### ISSUE THREAD

**Issue by PhenX** [jburrow/monaco-editor-code-review#16]
Hello, many code review systems allow commenting both sides when displaying diffs, and I think it would be great to have this possibility.

Thank you

**Comment by PhenX** [comment]
Nevermind my feature request, the review manager is linked to an editor, not a diff editor, so we can do both with getOriginalEditor and getModifiedEditor

**Comment by jburrow** [comment]
Yes that's right. Thanks for reaching out.
