### ISSUE TITLE
Cannot add comments on modified lines

### ISSUE THREAD

**Issue by PhenX** [jburrow/monaco-editor-code-review#17]
I cannot find a way to open the comment editor on modified lines in diff editor (side by side or not), is there an option I'm missing ?

**Comment by jburrow** [comment]
Great question... I will take a look this weekend

**Comment by PhenX** [comment]
Hello, it looks like a `z-index` issue, I had to add this rule to be able to trigger the comment form : 

```
.activeLineMarginClass {
    z-index: 10;
}
```

**Comment by jburrow** [comment]
ty - i added z-index; and pushed v0.25
