### ISSUE TITLE
Do you consider publishing to npm?

### ISSUE THREAD

**Issue by xiaodongxier** [jburrow/monaco-editor-code-review#220]
Great project, but it's a pity that I can't use it through npm in the project developed by vue. Is the project still under maintenance? Do you consider listing npm?
Anyway, it's a great project. Like it.

**Comment by jburrow** [comment]
Hi - It is listed here - https://www.npmjs.com/package/monaco-review

**Comment by jburrow** [comment]
https://www.npmjs.com/package/monaco-review
